apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  inputs:
    params:
      - name: url
        description: The URL of the Git repository to clone
        type: string
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        git clone $(inputs.params.url) /workspace/source